name = "Beamforming"
uuid = "bdfe4746-bf38-11e9-1e2c-db8d7c02fe8b"
authors = ["Andy Nowacki <a.nowacki@leeds.ac.uk>"]
version = "0.1.1"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Geodesics = "6aaf26a4-c633-11e8-35ae-8904cb805353"
Geodesy = "0ef565a4-170c-5f04-8de2-149903a85f3d"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Seis = "dd80f4d8-c2f6-58bd-9bd3-4635f134261d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DSP = "0.6, 0.7, 0.8"
FFTW = "1"
Geodesics = "0.2"
Geodesy = "0.5, 1"
RecipesBase = "0.7, 0.8, 1"
Seis = "0.3"
Statistics = "<0.0.1, 1"
julia = "1.6"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DelimitedFiles"]
